### ISSUE TITLE
Support for microsoft account authentication system

### ISSUE THREAD

**Issue by jiaaluo** [VidTuGit/In-Game-Account-Switcher#1]
As the title implies this a request for supporting Microsoft accounts.

New accounts created now are always going to be Microsoft accounts it doesn't hurt to be an early adopter with the switch happening likely at the end of 2021.

**Comment by VidTuGit** [comment]
This is actually a good idea, but implementation is kinda hard.

**Comment by jiaaluo** [comment]
You could possibly use ATLauncher and GDLauncher as references since they have Microsoft account support already supported.

**Comment by VidTuGit** [comment]
I already know how OAuth works, but due to the current situation with PayPal in my country, I'm currently unable to test it (because I'm currently unable to buy a new account). There're 3 ways to fix this:
1. Wait until I buy a new account.
2. Wait until migration.
3. Ask someone (probably one of my friends) for a Microsoft account for testing.

**Comment by VidTuGit** [comment]
Will be added in 7.1.

**Comment by VidTuGit** [comment]
Added in 7.1.0-pre1, however, it is an alpha version. There are probably some bugs, if you find one, report it here (on GitHub).
